"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
command_timeout = 1000

format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

right_format = """
$status\
$cmd_duration\
$jobs\
$direnv\
$conda\
$python\
$nodejs\
$ruby\
$golang\
$rust\
$dotnet\
$java\
$lua\
$perl\
$php\
$haskell\
$kubernetes\
$terraform\
$aws\
$azure\
$gcloud"""

[character]
success_symbol = "[❯](bold fg:76)"
error_symbol = "[❯](bold fg:196)"
vimcmd_symbol = "[❮](bold fg:76)"
vimcmd_replace_one_symbol = "[▶](bold fg:76)"
vimcmd_replace_symbol = "[▶](bold fg:76)"
vimcmd_visual_symbol = "[V](bold fg:76)"

[hostname]
ssh_only = true
format = "[$ssh_symbol$hostname]($style) "
style = "fg:180"
trim_at = "."

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "fg:31"
repo_root_style = "bold fg:39"
before_repo_root_style = "fg:103"
read_only = " "
read_only_style = "fg:196"
truncation_length = 8
truncation_symbol = ""
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
symbol = ""
style = "fg:76"
truncation_length = 32
truncation_symbol = "…"
always_show_remote = false

[git_commit]
format = "[@$hash]($style) "
style = "fg:76"
commit_hash_length = 8
only_detached = true

[git_state]
format = "[$state( $progress_current/$progress_total)]($style) "
style = "fg:196"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "fg:178"
conflicted = "[~$count](fg:196) "
ahead = "[⇡$count](fg:76) "
behind = "[⇣$count](fg:76) "
diverged = "[⇣$behind_count⇡$ahead_count](fg:76) "
stashed = "[*$count](fg:76) "
staged = "[+$count](fg:178) "
modified = "[!$count](fg:178) "
untracked = "[?$count](fg:39) "
deleted = "[!$count](fg:178) "
renamed = "[»$count](fg:178) "

[status]
disabled = false
format = "[$symbol$status]($style) "
symbol = "✘"
success_symbol = ""
style = "fg:160"
map_symbol = false
pipestatus = true
pipestatus_separator = "|"

[cmd_duration]
format = "[$duration]($style) "
style = "fg:101"
min_time = 3000
show_milliseconds = false

[jobs]
format = "[$symbol]($style) "
symbol = "✦"
style = "fg:70"
number_threshold = 999
symbol_threshold = 1

[direnv]
disabled = false
format = "[$symbol$loaded/$allowed]($style) "
style = "fg:178"
symbol = "direnv "

[conda]
format = "[$environment]($style) "
style = "fg:37"
symbol = ""
ignore_base = true

[python]
format = "[${pyenv_prefix}${version}${virtualenv}]($style) "
style = "fg:37"
symbol = ""
pyenv_version_name = true
python_binary = ["python3", "python"]

[nodejs]
format = "[$version]($style) "
style = "fg:70"
symbol = ""

[ruby]
format = "[$version]($style) "
style = "fg:168"
symbol = ""

[golang]
format = "[$version]($style) "
style = "fg:37"
symbol = ""

[rust]
format = "[$version]($style) "
style = "fg:37"
symbol = ""

[dotnet]
format = "[$version]($style) "
style = "fg:134"
symbol = ""

[java]
format = "[$version]($style) "
style = "fg:32"
symbol = ""

[lua]
format = "[$version]($style) "
style = "fg:32"
symbol = ""

[perl]
format = "[$version]($style) "
style = "fg:67"
symbol = ""

[php]
format = "[$version]($style) "
style = "fg:99"
symbol = ""

[haskell]
format = "[$version]($style) "
style = "fg:172"
symbol = ""

[kubernetes]
disabled = false
format = "[$context(/$namespace)]($style) "
style = "fg:134"
symbol = ""

[terraform]
format = "[$workspace]($style) "
style = "fg:38"
symbol = ""

[aws]
format = "[$profile( $region)]($style) "
style = "fg:208"
symbol = ""

[azure]
format = "[$subscription]($style) "
style = "fg:32"
symbol = ""
disabled = false

[gcloud]
format = "[$project]($style) "
style = "fg:32"
symbol = ""
